// Ionicons used by category icons: the curated set from the mobile app's
// `constants/category-icons.ts`. Regenerate this list if that file changes.
import {
  accessibility,
  airplane,
  alarm,
  at,
  bag,
  bandage,
  barChart,
  barcode,
  basket,
  basketball,
  bed,
  beer,
  bicycle,
  boat,
  body,
  bonfire,
  book,
  bookmark,
  bowlingBall,
  briefcase,
  brush,
  bug,
  bulb,
  bus,
  cafe,
  calculator,
  call,
  camera,
  car,
  carSport,
  card,
  cart,
  cash,
  chatbubble,
  chatbubbles,
  cloud,
  cloudy,
  codeSlash,
  colorPalette,
  compass,
  construct,
  cut,
  desktop,
  diamond,
  dice,
  documentText,
  download,
  ear,
  earth,
  ellipsisHorizontal,
  eye,
  fastFood,
  film,
  fish,
  fitness,
  flag,
  flame,
  flash,
  flower,
  football,
  gameController,
  gift,
  globe,
  golf,
  hammer,
  handLeft,
  happy,
  headset,
  heart,
  home,
  hourglass,
  iceCream,
  key,
  laptop,
  leaf,
  library,
  link,
  lockClosed,
  logoBitcoin,
  logoUsd,
  mail,
  map,
  medical,
  medkit,
  megaphone,
  moon,
  musicalNote,
  musicalNotes,
  navigate,
  newspaper,
  notifications,
  nutrition,
  paw,
  pencil,
  people,
  person,
  personAdd,
  pieChart,
  pizza,
  pricetag,
  pricetags,
  pulse,
  qrCode,
  rainy,
  receipt,
  restaurant,
  rocket,
  sad,
  school,
  settings,
  share,
  shield,
  shirt,
  snow,
  sparkles,
  star,
  statsChart,
  storefront,
  subway,
  sunny,
  tennisball,
  thermometer,
  ticket,
  time,
  trailSign,
  train,
  trash,
  trendingDown,
  trendingUp,
  trophy,
  tv,
  wallet,
  water,
  wine,
} from 'ionicons/icons';

import { parseIcon } from '@/utils/icon';

/** Ionicons name (as stored in `categories.icon`, e.g. "fast-food") to its SVG data URI. */
export const CATEGORY_ICON_SOURCES: Record<string, string | undefined> = {
  accessibility,
  airplane,
  alarm,
  at,
  bag,
  bandage,
  'bar-chart': barChart,
  barcode,
  basket,
  basketball,
  bed,
  beer,
  bicycle,
  boat,
  body,
  bonfire,
  book,
  bookmark,
  'bowling-ball': bowlingBall,
  briefcase,
  brush,
  bug,
  bulb,
  bus,
  cafe,
  calculator,
  call,
  camera,
  car,
  'car-sport': carSport,
  card,
  cart,
  cash,
  chatbubble,
  chatbubbles,
  cloud,
  cloudy,
  'code-slash': codeSlash,
  'color-palette': colorPalette,
  compass,
  construct,
  cut,
  desktop,
  diamond,
  dice,
  'document-text': documentText,
  download,
  ear,
  earth,
  'ellipsis-horizontal': ellipsisHorizontal,
  eye,
  'fast-food': fastFood,
  film,
  fish,
  fitness,
  flag,
  flame,
  flash,
  flower,
  football,
  'game-controller': gameController,
  gift,
  globe,
  golf,
  hammer,
  'hand-left': handLeft,
  happy,
  headset,
  heart,
  home,
  hourglass,
  'ice-cream': iceCream,
  key,
  laptop,
  leaf,
  library,
  link,
  'lock-closed': lockClosed,
  'logo-bitcoin': logoBitcoin,
  'logo-usd': logoUsd,
  mail,
  map,
  medical,
  medkit,
  megaphone,
  moon,
  'musical-note': musicalNote,
  'musical-notes': musicalNotes,
  navigate,
  newspaper,
  notifications,
  nutrition,
  paw,
  pencil,
  people,
  person,
  'person-add': personAdd,
  'pie-chart': pieChart,
  pizza,
  pricetag,
  pricetags,
  pulse,
  'qr-code': qrCode,
  rainy,
  receipt,
  restaurant,
  rocket,
  sad,
  school,
  settings,
  share,
  shield,
  shirt,
  snow,
  sparkles,
  star,
  'stats-chart': statsChart,
  storefront,
  subway,
  sunny,
  tennisball,
  thermometer,
  ticket,
  time,
  'trail-sign': trailSign,
  train,
  trash,
  'trending-down': trendingDown,
  'trending-up': trendingUp,
  trophy,
  tv,
  wallet,
  water,
  wine,
};

/**
 * Inline SVG markup for a stored category icon ("Ionicons/fast-food"), or null when the icon
 * is missing or not in the curated set. The markup comes from the `ionicons` package.
 */
export function getCategoryIconSvg(icon: string | null): string | null {
  const parsed = icon ? parseIcon(icon) : null;
  if (!parsed || parsed.library !== 'Ionicons') return null;
  const source = CATEGORY_ICON_SOURCES[parsed.name];
  if (!source) return null;
  const start = source.indexOf('<svg');
  return start === -1 ? null : source.slice(start);
}
